app/controllers/users/routes.py
from operator import and_, or_
from flask import render_template, flash, redirect, url_for, Blueprint, request, abort
from app.controllers.users.form import (
    LoginForm, CreateUserForm, UpdateUserForm, UpdatePassWordUserForm, SelecaoFormUser)
from app.controllers.main.form import Areas
from app import db, bcrypt
from sqlalchemy import or_, and_
from app.models.bdMonitora import (Permissoes, Users, Enderecos, Sites)
from flask_login import login_user, current_user, logout_user, login_required


user = Blueprint('user', __name__)

@user.route('/consulta', methods=['POST'])
def consulta():
    if current_user.permissoes[0].adminUser and current_user.ativo:
        form = SelecaoFormUser()
        if form.validate_on_submit():
            consulta = '%'+form.consulta.data+'%'
            selection = form.selection.data
            if selection == 'Nome':
                users = db.session.query(Users.id, Users.nome.label('userNome'), Users.login, Users.email, Sites.nome.label('siteNome')).join(Users, Sites.id == Users.idSite).filter(and_(Sites.id==form.idSite.data, Users.nome.like(consulta))).all()
            elif selection == 'Login':
                users = db.session.query(Users.id, Users.nome.label('userNome'), Users.login, Users.email, Sites.nome.label('siteNome')).join(Users, Sites.id == Users.idSite).filter(and_(Sites.id==form.idSite.data, Users.login.like(consulta))).all()
            elif selection == 'Email':
                users = db.session.query(Users.id, Users.nome.label('userNome'), Users.login, Users.email, Sites.nome.label('siteNome')).join(Users, Sites.id == Users.idSite).filter(and_(Sites.id==form.idSite.data, Users.email.like(consulta))).all()
            else:
                users = db.session.query(Users.id, Users.nome.label('userNome'), Users.login, Users.email, Sites.nome.label('siteNome')).join(Users, Sites.id == Users.idSite).filter(Sites.id == form.idSite.data).all()
            
            return render_template('users/usuario.html', title='Usuários', usuarios=users, idSite=form.idSite.data, form=form)
        else:
            users = db.session.query(Users.id, Users.nome.label('userNome'), Users.login, Users.email, Sites.nome.label('siteNome')).join(Users, Sites.id == Users.idSite).filter(Sites.id == form.idSite.data).all()
            return render_template('users/usuario.html', title='Usuários', usuarios=users, idSite=form.idSite.data, form=form)
    else:
        abort(403)
    


@user.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    try:
        if form.validate_on_submit():
            user = Users.query.filter_by(
                login=form.login.data.lower()).first_or_404()
            if user and bcrypt.check_password_hash(user.senha, form.password.data.lower()) and user.ativo:
                login_user(user=user, remember=form.remember.data)
                next_page = request.args.get('next')
                return redirect(next_page) if next_page else redirect(url_for('main.home'))
            elif not user.ativo:
                abort(403)
            else:
                flash('Error, Verifique Login/Senha!', 'danger')
    except Exception as e:
        print(f'Erro que vou ver qual é: {e}')
        abort(403)

    return render_template('users/login.html', title='Login', form=form)


@user.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@user.route('/createAdmin')
def createAdmin():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))

    hashed_password = bcrypt.generate_password_hash(
        '#mapfre@1234#').decode('utf-8')

    users = Users.query.all()

    if not users:
        try:
            endereco = Enderecos(
                rua='Coronel Jose Augusto de Oliveira Salles', cidade='São Carlos - SP', cep=13570820)
            db.session.add(endereco)
            db.session.commit()
        except Exception as e:
            db.session.flush()
            db.session.rollback()
            # print(f'Erro: {e}')

        try:
            site = Sites(nome='Mapfre - (São Carlos)', idEndereco=endereco.id)
            db.session.add(site)
            db.session.commit()
            areas = ['Estoque', 'Inventario', 'Descarte']
            for area in areas:
                a = Areas(nome=area, site=[site])
                db.session.add(a)
                db.session.commit()
        except Exception as e:
            db.session.flush()
            db.session.rollback()
            # print(f'Erro: {e}')

        try:
            permissoes = Permissoes(leitura=True, escrita=True, adminUser=True)
            db.session.add(permissoes)
            db.session.commit()
        except Exception as e:
            db.session.flush()
            db.session.rollback()
            print(f"Erro: {e}")

        try:
            permissoes = Permissoes.query.all()
        except Exception as e:
            db.session.flush()
            db.session.rollback()
            # print(f'Erro: {e}')

        try:
            # print(type(permissoes))
            user = Users(nome='Administrador', login='admin', senha=hashed_password,
                         email='admin@bbmapfre.com.br', permissoes=permissoes, ativo=True, idSite=site.id)
            db.session.add(user)
            db.session.commit()
        except Exception as e:
            db.session.flush()
            db.session.rollback()
            print(f'Erro: {e}')

        flash('Login Administrador criado com sucesso!', 'success')
        return redirect(url_for('main.home'))
    else:
        flash('Login Administrador já existe!', 'danger')
        return redirect(url_for('main.home'))


@user.route('/usuario/site')
@login_required
def usuarioSite():
    if current_user.permissoes[0].adminUser and current_user.ativo:
        sites = Sites.query.all()
        return render_template('users/users_site.html', sites=sites, title='Site do Usuário', legenda='Lista de Sites', descricao='Selecione o Site que deseja acessar.')
    else:
        abort(403)


@user.route('/usuarios/site/<int:idSite>')
@login_required
def lista_usuario(idSite):

    if current_user.permissoes[0].adminUser and current_user.ativo:
        form = SelecaoFormUser()
        users = db.session.query(Users.id, Users.nome.label('userNome'), Users.login, Users.email, Sites.nome.label(
            'siteNome')).join(Users, Sites.id == Users.idSite).filter(Sites.id == idSite).all()
        # print(users[1]['siteNome'])
        form.idSite.data = idSite
        return render_template('users/usuario.html', title='Usuários', usuarios=users, idSite=idSite, form=form)
    else:
        abort(403)


@user.route('/usuario/novo/<int:idSite>',  methods=['GET', 'POST'])
@login_required
def novo_usuario(idSite):
    form = CreateUserForm()
    # permissoes = db.session.query(Permissoes).join(Users.permissoes).filter(or_(Permissoes.leitura==form.r.data, Permissoes.escrita==form.w.data, Permissoes.adminUser==form.adminUser.data)).first()
    # print(permissoes)
    if current_user.permissoes[0].adminUser and current_user.ativo:
        if form.validate_on_submit():
            hashed_password = bcrypt.generate_password_hash(
                form.password.data).decode('utf-8')
            try:
                permissoes = Permissoes(
                    leitura=form.leitura.data, escrita=form.escrita.data, adminUser=form.adminUser.data)
                db.session.add(permissoes)
                db.session.commit()
            except Exception as e:
                print(f'Error: {e}')
            site = Sites.query.filter_by(
                nome=form.siteSelect.data).first_or_404()
            if site:
                user = Users(nome=form.nome.data.upper(), login=form.login.data.lower(), senha=hashed_password,
                             email=form.email.data.lower(), ativo=form.ativo.data, permissoes=[permissoes], idSite=site.id)
                db.session.add(user)
                db.session.commit()
                flash(
                    f'Conta criada com sucesso para: {form.nome.data}!', 'success')
            return redirect(url_for('user.lista_usuario', idSite=site.id))
        else:
            site = Sites.query.get(idSite)
            form.siteSelect.choices = [site.nome]
            return render_template('users/criar_usuario.html', title='Novo usuário', form=form, idSite=idSite)
    else:
        abort(403)


@user.route('/usuarioUpdate',  methods=['GET', 'POST'])
@login_required
def update_usuario():
    if current_user.permissoes[0].adminUser and current_user.ativo:
        form = UpdateUserForm()
        if request.method == 'POST' and request.form.get('idUser') and request.form.get('idSite'):
            user = db.session.query(Users.nome, Users.login, Users.email, Users.ativo, Permissoes.adminUser, Permissoes.escrita,
                                    Permissoes.leitura).join(Users.permissoes).filter(Users.id == request.form.get('idUser')).first()
            form.idUsuario.data = request.form.get('idUser')
            form.idSite.data = request.form.get('idSite')
            form.nome.data = user.nome
            form.login.data = user.login
            form.email.data = user.email
            form.ativo.data = user.ativo
            form.adminUser.data = user.adminUser
            form.leitura.data = user.leitura
            form.escrita.data = user.escrita
            return render_template('users/update_usuario.html', title='Editar usuário', legenda='Update dados do Usuário', form=form)

        elif form.validate_on_submit():
            user = Users.query.get(form.idUsuario.data)
            permissoes = db.session.query(Permissoes).join(
                Users.permissoes).filter(Users.id == form.idUsuario.data).first()
            user.nome = form.nome.data
            user.login = form.login.data

app/templates/users/criar_usuario.html
{% extends 'layout2.html' %}
{% block content %}
  <header>
    <div class="jumbotron jumbotron-fluid mt-4">
      <div class="container">
        <h1 class="display-4"><i class="fa-solid fa-users"></i> Cadastrar novo usuário</h1>
        <p class="lead">
        Informe os dados para cadastrar novo usuário no sistema.
        </p>
      </div>
    </div>
  </header>
  <main>
    <div class="content-section mt-4">
      <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
          <!-- <legend class="border-bottom mb-4">Cadastro usuário</legend> -->
          <div class="form-group">
            {{ form.nome.label(class='form-control-label') }} {% if form.nome.errors
            %} {{ form.nome(class='form-control form-control-lg is-invalid')}}
            <div class="invalid-feedback">
              {% for error in form.nome.errors %}
              <span>{{ error }}</span>
              {% endfor %}
            </div>
            {% else %} {{ form.nome(class='form-control
            form-control-lg',placeholder='Nome Completo')}} {% endif %}
          </div>
          <div class="form-row">
            <div class="form-group col-md-6">
              {{ form.login.label(class='form-control-label') }} {% if
              form.login.errors %} {{ form.login(class='form-control form-control-lg
              is-invalid')}}
              <div class="invalid-feedback">
                {% for error in form.login.errors %}
                <span>{{ error }}</span>
                {% endfor %}
              </div>
              {% else %} {{ form.login(class='form-control form-control-lg',
              placeholder='Login de rede')}} {% endif %}
            </div>
            <div class="form-group col-md-6">
              {{form.siteSelect.label(class="form-group mr-2")}}
              {{form.siteSelect(class='custom-select mr-sm-2"')}}
            </div>
          </div>
          <div class="form-group">
            {{ form.email.label(class='form-control-label') }} {% if
            form.email.errors %} {{ form.email(class='form-control form-control-lg
            is-invalid')}}
            <div class="invalid-feedback">
              {% for error in form.email.errors %}
              <span>{{ error }}</span>
              {% endfor %}
            </div>
            {% else %} {{ form.email(class='form-control form-control-lg',
            placeholder='informe e-mail')}} {% endif %}
          </div>
          <div class="form-row">
            <div class="form-group col-md-6">
              {{ form.password.label(class='form-control-label') }} {% if
              form.password.errors %} {{ form.password(class='form-control
              form-control-lg is-invalid')}}
              <div class="invalid-feedback">
                {% for error in form.password.errors %}
                <span>{{ error }}</span>
                {% endfor %}
              </div>
              {% else %} {{ form.password(class='form-control form-control-lg',
              placeholder='Informe a senha')}} {% endif %}
            </div>
            <div class="form-group col-md-6">
              {{ form.confiPassword.label(class='form-control-label') }} {% if
              form.confiPassword.errors %} {{ form.confiPassword(class='form-control
              form-control-lg is-invalid')}}
              <div class="invalid-feedback">
                {% for error in form.confiPassword.errors %}
                <span>{{ error }}</span>
                {% endfor %}
              </div>
              {% else %} {{ form.confiPassword(class='form-control form-control-lg',
              placeholder='Confirme a senha')}} {% endif %}
            </div>
          </div>
          <div class="form-row">
            <div class="custom-control custom-switch">
              {{form.adminUser(class="custom-control-input")}}
              {{form.adminUser.label(class="custom-control-label ml-1")}}
            </div>
            <div class="custom-control custom-switch">
              {{form.leitura(class="custom-control-input")}}
              {{form.leitura.label(class="custom-control-label ml-4")}}
            </div>
            <div class="custom-control custom-switch">
              {{form.escrita(class="custom-control-input")}}
              {{form.escrita.label(class="custom-control-label ml-4")}}
            </div>
            <div class="custom-control custom-switch">
              {{form.ativo(class="custom-control-input")}}
              {{form.ativo.label(class="custom-control-label ml-4")}}
            </div>
          </div>
          <div class="form-group mt-4">
            {{ form.submit(class='btn btn-outline-primary')}}
            <a href="{{url_for('user.lista_usuario', idSite=idSite)}}" class="btn btn-outline-danger ml-3">Cancelar</a>
          </div>
        </fieldset>
      </form>
    </div>
  </main>
{% endblock content %}

app/templates/users/login.html
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{url_for('static', filename='css/bootstrap.min.css')}}">
    <link rel="stylesheet" href="{{url_for('static', filename='css/login.css')}}">
    {% if title %}
    <title>Monitora - {{title}}</title>
    {% else %}
    <table>Monitora</table>
    {% endif %}
</head>

<body>
    <form class="form-signin", method="Post", action="">
        <h1 class="h3 mb-3 font-weight-normal">Faça Seu Login</h1>
        {% with messages = get_flashed_messages(with_categories=true)%}
            {% if messages %}
                {% for category, message in messages %}
                    <div class="alert alert-{{category}}">
                        {{message}}
                    </div>
                {% endfor %}
            {%endif%}
        {%endwith%}
        {{form.hidden_tag()}}
        {{ form.login.label(class='sr-only') }}
        {% if form.login.errors %}
            {{ form.login(class='form-control form-control-lg is-invalid') }}
            <div class="invalid-feedback">
                {% for error in form.login.errors %}
                    <span> {{ error }}</span>
                {% endfor %}
            </div>
        {% else %}
            {{ form.login(class='form-control', placeholder='Login') }}
        {% endif %}

        {{ form.password.label(class='sr-only')}}
        {{ form.password(class='form-control', placeholder='Password')}}

        <div class="ckeckbox mb-3">
            {{form.remember()}}
            {{form.remember.label()}}
        </div>

        {{form.submit(class='btn btn-lg btn-primary btn-block')}}

        <p class="mt-5 mb-3 text-muted">&copy; 2022-2022</p>

    </form>

    <script src="{{url_for('static', filename='js/jquery.min.js')}}"></script>
    <script src="{{url_for('static', filename='js/popper.min.js')}}"></script>
    <script src="{{url_for('static', filename='js/bootstrap.min.js')}}"></script>
</body>

</html>

app/templates/users/passWord_usuario.html
{% extends 'layout2.html' %}
{% block content %}
  <header>
    <div class="jumbotron jumbotron-fluid mt-4">
      <div class="container">
        <h1 class="display-4 text-primary"><i class="fa-solid fa-pen-to-square"></i> {{legenda}}</h1>
        <p class="lead font-weight-normal">Informe a nova senha do usuário no sistema.</p>
      </div>
    </div>
  </header>
  <main>
    <div class="content-section mt-4">
      {{id_user}}
      <form method="POST" action="{{url_for('user.updatePassword_usuario')}}">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
          <div class="form-row">
            <div class="form-group col-md-6">
              {{ form.password.label(class='form-control-label') }} {% if
              form.password.errors %} {{ form.password(class='form-control
              form-control-lg is-invalid')}}
              <div class="invalid-feedback">
                {% for error in form.password.errors %}
                <span>{{ error }}</span>
                {% endfor %}
              </div>
              {% else %} {{ form.password(class='form-control form-control-lg',
              placeholder='Informe a senha')}} {% endif %}
            </div>
            <div class="form-group col-md-6">
              {{ form.confiPassword.label(class='form-control-label') }} {% if
              form.confiPassword.errors %} {{ form.confiPassword(class='form-control
              form-control-lg is-invalid')}}
              <div class="invalid-feedback">
                {% for error in form.confiPassword.errors %}
                <span>{{ error }}</span>
                {% endfor %}
              </div>
              {% else %} {{ form.confiPassword(class='form-control form-control-lg',
              placeholder='Confirme a senha')}} {% endif %}
            </div>
          </div>
          <div class="form-group mt-4">
            {{ form.submit(class='btn btn-outline-primary')}}
            <a href="{{url_for('user.lista_usuario', idSite=form.idSite.data)}}" class="btn btn-outline-danger ml-3">Cancelar</a>
          </div>
        </fieldset>
      </form>
    </div>
  </main>
{% endblock content %}

app/templates/users/update_usuario.html
{% extends 'layout2.html' %}
{% block content %}
  <header>
    <div class="jumbotron jumbotron-fluid mt-4">
      <div class="container">
        <h1 class="display-4 text-primary"><i class="fa-solid fa-wrench"></i> {{legenda}}</h1>
        <p class="lead text-secondary mt-4 mb-1">
         Verifique os dados para atualizar usuário no sistema.
        </p>
      </div>
    </div>
  </header>
  <main>
    <div class="content-section mt-4">
      <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
          <!-- <legend class="border-bottom mb-4">Cadastro usuário</legend> -->
          <div class="form-group">
            {{ form.nome.label(class='form-control-label') }} {% if form.nome.errors
            %} {{ form.nome(class='form-control form-control-lg is-invalid')}}
            <div class="invalid-feedback">
              {% for error in form.nome.errors %}
              <span>{{ error }}</span>
              {% endfor %}
            </div>
            {% else %} {{ form.nome(class='form-control
            form-control-lg',placeholder='Nome do site')}} {% endif %}
          </div>
          <div class="form-group">
            {{ form.email.label(class='form-control-label') }} {% if form.email.errors
            %} {{ form.email(class='form-control form-control-lg is-invalid')}}
            <div class="invalid-feedback">
              {% for error in form.email.errors %}
              <span>{{ error }}</span>
              {% endfor %}
            </div>
            {% else %} {{ form.email(class='form-control
            form-control-lg',placeholder='email do site')}} {% endif %}
          </div>
          <div class="form-row">
            <div class="col-6">
              {{ form.login.label(class='form-control-label') }} {% if form.login.errors
              %} {{ form.login(class='form-control form-control-lg is-invalid')}}
              <div class="invalid-feedback">
                {% for error in form.login.errors %}
                <span>{{ error }}</span>
                {% endfor %}
              </div>
              {% else %} {{ form.login(class='form-control
              form-control-lg',placeholder='login do site')}} {% endif %}
            </div>
            <div class="col-6">
              {{ form.siteSelect.label(class='form-control-label') }} {% if form.siteSelect.errors
              %} {{ form.siteSelect(class='form-control form-control-lg is-invalid')}}
              <div class="invalid-feedback">
                {% for error in form.siteSelect.errors %}
                <span>{{ error }}</span>
                {% endfor %}
              </div>
              {% else %} {{ form.siteSelect(class='form-control
              form-control-lg',placeholder='siteSelect do site')}} {% endif %}
            </div>
          </div>
          <div class="form-row mt-4">
            <div class="custom-control custom-switch">
              {{form.adminUser(class="custom-control-input")}}
              {{form.adminUser.label(class="custom-control-label ml-1")}}
            </div>
            <div class="custom-control custom-switch">
              {{form.leitura(class="custom-control-input")}}
              {{form.leitura.label(class="custom-control-label ml-4")}}
            </div>
            <div class="custom-control custom-switch">
              {{form.escrita(class="custom-control-input")}}
              {{form.escrita.label(class="custom-control-label ml-4")}}
            </div>
            <div class="custom-control custom-switch">
              {{form.ativo(class="custom-control-input")}}
              {{form.ativo.label(class="custom-control-label ml-4")}}
            </div>
          </div>
          <div class="form-group mt-4">
            {{ form.submit(class='btn btn-outline-primary')}}
            <a href="{{url_for('user.lista_usuario', idSite=form.idSite.data)}}" class="btn btn-outline-warning ml-3"><i class="fa-solid fa-xmark"></i> Cancelar</a>
          </div>
        </fieldset>
      </form>
    </div>
  </main>
{% endblock content %}

app/templates/users/users_site.html
{% extends 'layout2.html' %}
{% block content %}
  <header>
    <div class="jumbotron jumbotron-fluid mt-4">
      <div class="container">
        <h1 class="display-4"><i class="fa-solid fa-clipboard-list"></i> {{legenda}}</h1>
        <p class="lead">{{descricao}}</p>
      </div>
    </div>
    <table class="table table-hover text-center">
      <thead>
        <tr class="table-secondary">
          <th scope="col"><a href="#">Id</a></th>
          <th scope="col"><a href="#">Site do Usuário</a></th>
          <th scope="col">Ação</th>
        </tr>
      </thead>
      <tbody>
        {% for site in sites%}
        <tr>
          <th scope="row">{{site.id}}</th>
          <td>{{site.nome}}</td>
          {% if site %}
            <td><a class="btn btn-info" href="{{url_for('user.lista_usuario', idSite=site.id)}}" role="button"><i class="fa-solid fa-pen-to-square"></i> Acessar</a></td>
          {% endif %}
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </main>
{% endblock content %}

app/templates/users/usuario.html
{% extends 'layout2.html' %}
{% block content %}
  <header>
    <div class="jumbotron jumbotron-fluid mt-4">
      <div class="container">
        <h1 class="display-4"><i class="fa-solid fa-users"></i> Usuários cadastrados no sistema</h1>
        <p class="lead">
          Relação de todos os usuários cadastrado no sistema.
        </p>
      </div>
    </div>
    <form action="{{url_for('user.consulta')}}" method="POST" class="ml-3 mb-4">
      {{ form.hidden_tag() }}
      <div class="form-group">
        <div class="row">
          {{form.consulta(class='form-control col-md-5', placeholder='Digita aqui a consulta ...')}}
          {{form.selection(class='form-control col-md-2 ml-3')}}
          <button type="submit" class="btn btn-success ml-4"><i class="fa-solid fa-magnifying-glass"></i> Consultar</button>
          <a class="btn btn-primary ml-3" href="{{url_for('user.novo_usuario', idSite=idSite)}}" role="button"><i class="fa-solid fa-desktop"></i> Novo</a>
          <a class="btn btn-warning ml-3" href="#" role="button"><i class="fa-regular fa-file-pdf"></i> PDF</a>
        </div>
      </div>
    </form>
  </header>
  <main>
    <table class="table table-hover text-center">
      <thead>
        <tr class="table-secondary">
          <th scope="col"><a href="#">Id</a></th>
          <th scope="col"><a href="#">Nome</a></th>
          <th scope="col"><a href="#">Login</a></th>
          <th scope="col"><a href="#">Email</a></th>
          <th scope="col"><a href="#">Site</a></th>
          <th scope="col">Ação</th>
        </tr>
      </thead>
      <tbody>
        {% for users in usuarios%}
          {% if users.login == 'admin'%}
          {% else %}
            <tr>
              <th scope="row">{{users.id}}</th>
              <td>{{users.userNome}}</td>
              <td>{{users.login}}</td>
              <td>{{users.email}}</td>
              <td>{{users.siteNome}}</td>
              <td>
                <!-- <a class="btn btn-info" href="{{url_for('user.update_usuario', id_user=users.id)}}" role="button"><i class="fa-solid fa-pen-to-square"></i> Editar</a> -->
                <a href="" onclick="editarUser('{{users.id}}', '{{idSite}}')" role="button" class="btn btn-danger ml-3" data-toggle="modal" data-target="#editarUser"><i class="fa-solid fa-pen-to-square"></i></a>
              </td>
            </tr>
          {% endif %}
        {% endfor %}
      </tbody>
    </table>
    {% for campo, erros in form.errors.items() %} 
      <div class="alert alert-danger" role="alert"> 
        {{ form[campo].label }} : {{''.join(erros)}}</h5>
      </div>
    {% endfor %}
  </main>

  <!-- Modal -->
  <div class="modal fade" id="editarUser" tabindex="-1" role="dialog" aria-labelledby="editarUserTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLongTitle">O que deseja fazer?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <input type="hidden" name="id_user" id="id_user">
          <input type="hidden" name="id_site" id="id_site">
          <div class="form-row">
            <div class="col-md-6">
              <a class="btn btn-warning ml-4" onclick="updateURLUser()" role="button"><i class="fa-solid fa-pen-to-square"></i> Atualizar Dados</a>
            </div>
            <div class="col-md-6">
              <a class="btn btn-warning ml-4" onclick="trocarSenhaURLUser()" role="button"><i class="fa-solid fa-pen-to-square"></i> Trocar Senha</a>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}