app/controllers/equipamento/routes.py
from flask import render_template, Blueprint, flash, redirect, url_for, request, abort
from flask_login import login_required, current_user
from app.controllers.equipamento.form_disposivo import InventariosNovoForm, TipoInventarioForm, UpdateInventariosForm, InventarioForm, MudancalayoutForm
from app.controllers.equipamento.monitora import Monitora
from app.models.bdMonitora import Areas, Computadores, PontoAtendimentos, TipoEquipamentos, DispositivosEquipamentos, Sites, Status
from app import db
from sqlalchemy import exc, and_
from datetime import datetime
from pytz import timezone

equipamento = Blueprint('equipamento', __name__)


@equipamento.route('/inventarios/view')
@login_required
def inventarioView():
    if (current_user.permissoes[0].leitura or current_user.permissoes[0].escrita) and current_user.ativo:
        form = InventarioForm()
        db.session.flush()
        try:
            # inventarios = db.session.query(Sites.id, Sites.nome).join(DispositivosEquipamentos, Sites.id==DispositivosEquipamentos.idSite).join(Areas, DispositivosEquipamentos.idArea==Areas.id).filter(Areas.nome=='Inventario').distinct(Sites.id).all()
            sites = db.session.query(Sites).all()
            # print(inventarios)
        except Exception as e:
            print(f'Error: {e}')
        return render_template('equipamentos/inventario_view.html', title='Inventários', legenda='Inventários cadastrados', descricao='Relação de todos os Inventarios no Sistema', sites=sites, form=form)
    else:
        abort(403)


@equipamento.route('/inventario/<int:idSite>/consulta')
@login_required
def consultaInventario(idSite):
    if (current_user.permissoes[0].leitura or current_user.permissoes[0].escrita) and current_user.ativo:
        form = InventarioForm()
        site = Sites.query.get(idSite)
        try:
            db.session.flush()
            computadores = db.session.query(DispositivosEquipamentos.id, DispositivosEquipamentos.serial, DispositivosEquipamentos.patrimonio, DispositivosEquipamentos.hostname, TipoEquipamentos.nome, PontoAtendimentos.descricao, Sites.nome.label('site')).join(
                Sites, DispositivosEquipamentos.idSite == Sites.id).join(TipoEquipamentos, DispositivosEquipamentos.idTipo == TipoEquipamentos.id).join(Areas, DispositivosEquipamentos.idArea == Areas.id).join(Computadores, DispositivosEquipamentos.id == Computadores.idDispositosEquipamento).join(PontoAtendimentos, Computadores.idPontoAtendimento == PontoAtendimentos.id).filter(and_(DispositivosEquipamentos.idSite == idSite, Areas.nome == 'Inventario')).all()
        except Exception as e:
            print(f'Error: {e}')
        if computadores:
            return render_template('equipamentos/inventario.html', title='Inventários', legenda='Dispositivos cadastrados', descricao=f'{computadores[0].site} - Relação de todos os dispositivos cadastrados no Inventário', computadores=computadores, form=form, idSite=idSite)
        else:
            return render_template('equipamentos/inventario.html', title='Inventários', legenda='Dispositivos cadastrados', descricao=f'{site.nome} - Relação de todos os dispositivos cadastrados no Inventário', computadores=computadores, form=form, idSite=idSite)
    else:
        abort(403)


@equipamento.route('/inventario', methods=['GET', 'POST'])
@login_required
def inventario():
    if (current_user.permissoes[0].leitura or current_user.permissoes[0].escrita) and current_user.ativo:
        form = InventarioForm()
        if request.method == 'POST':
            consult = '%'+form.consulta.data+'%'
            if form.selection.data == 'Serial':
                try:
                    inventarios = []
                    invent = db.session.query(DispositivosEquipamentos.id, DispositivosEquipamentos.serial, DispositivosEquipamentos.hostname, DispositivosEquipamentos.patrimonio, PontoAtendimentos.descricaoPa, TipoEquipamentos.nome).join(
                        DispositivosEquipamentos, PontoAtendimentos.id == DispositivosEquipamentos.idLocalPa).join(DispositivosEquipamentos.tipo).filter(DispositivosEquipamentos.serial.like(consult)).first_or_404()
                    inventarios.append(invent)
                    if not invent:
                        flash(
                            'Verifique dados informados, nada foi localizado!', 'danger')
                    form.consulta.data = ''
                except Exception as e:
                    print(f'Erro! {e}')
            elif form.selection.data == 'Patrimônio':
                try:
                    inventarios = []
                    invent = db.session.query(DispositivosEquipamentos.id, DispositivosEquipamentos.serial, DispositivosEquipamentos.hostname, DispositivosEquipamentos.patrimonio, PontoAtendimentos.descricaoPa, TipoEquipamentos.nome).join(
                        DispositivosEquipamentos, PontoAtendimentos.id == DispositivosEquipamentos.idLocalPa).join(DispositivosEquipamentos.tipo).filter(DispositivosEquipamentos.patrimonio.like(consult)).first_or_404()
                    inventarios.append(invent)
                    if not invent:
                        flash(
                            'Verifique dados informados, nada foi localizado!', 'danger')
                        try:
                            inventarios = db.session.query(DispositivosEquipamentos.id, DispositivosEquipamentos.serial, DispositivosEquipamentos.hostname, DispositivosEquipamentos.patrimonio, PontoAtendimentos.descricaoPa, TipoEquipamentos.nome).join(
                                DispositivosEquipamentos.tipo).filter(DispositivosEquipamentos.idLocalPa == PontoAtendimentos.id).order_by(DispositivosEquipamentos.id).all()
                        except Exception as e:
                            # print(f"Erro! {e}")
                            pass
                        form.consulta.data = ''

                except Exception as e:
                    print(f'Erro! {e}')
            elif form.selection.data == 'Local':
                try:
                    inventarios = []
                    invent = db.session.query(DispositivosEquipamentos.id, DispositivosEquipamentos.serial, DispositivosEquipamentos.hostname, DispositivosEquipamentos.patrimonio, PontoAtendimentos.descricaoPa, TipoEquipamentos.nome).join(
                        DispositivosEquipamentos, PontoAtendimentos.id == DispositivosEquipamentos.idLocalPa).join(DispositivosEquipamentos.tipo).filter(PontoAtendimentos.descricaoPa.like(consult)).first_or_404()
                    inventarios.append(invent)
                    if not invent:
                        flash(
                            'Verifique dados informados, nada foi localizado!', 'danger')
                        try:
                            inventarios = db.session.query(DispositivosEquipamentos.id, DispositivosEquipamentos.serial, DispositivosEquipamentos.hostname, DispositivosEquipamentos.patrimonio, PontoAtendimentos.descricaoPa, TipoEquipamentos.nome).join(
                                DispositivosEquipamentos.tipo).filter(DispositivosEquipamentos.idLocalPa == PontoAtendimentos.id).order_by(DispositivosEquipamentos.id).all()
                        except Exception as e:
                            # print(f"Erro! {e}")
                            pass
                        form.consulta.data = ''
                except Exception as e:
                    print(f'Erro! {e}')

        elif request.method == 'GET':
            try:
                # inventarios = db.session.query(DispositivosEquipamentos.id, DispositivosEquipamentos.serial, DispositivosEquipamentos.hostname, DispositivosEquipamentos.patrimonio, PontoAtendimentos.descricaoPa, Tipos.nome).join(
                #     DispositivosEquipamentos.tipo).filter(DispositivosEquipamentos.idLocalPa == PontoAtendimentos.id).order_by(DispositivosEquipamentos.id).all()
                inventarios = []
            except Exception as e:
                # print(f"Erro! {e}")
                pass
        return render_template('equipamentos/inventario.html', title='Inventário', equipamentos=inventarios, form=form)
    else:
        abort(403)


@equipamento.route('/dispotivo/<int:idSite>/novo', methods=['GET', 'POST'])
@login_required
def novo_equipamento(idSite):
    if (current_user.permissoes[0].leitura or current_user.permissoes[0].escrita) and current_user.ativo:
        form = InventariosNovoForm()
        try:
            site = Sites.query.get(idSite)
        except Exception as e:
            db.session.flush()
            print(f'Error: {e}')
        if form.validate_on_submit():
            try:
                area = db.session.query(Areas).join(Areas.site).filter(
                    and_(Sites.id == form.idSite.data, Areas.nome == 'Inventario')).first()
                tipoDispositivo = db.session.query(TipoEquipamentos).join(TipoEquipamentos.site).filter(
                    and_(Sites.id == form.idSite.data, TipoEquipamentos.nome == form.tipoDispositivo.data)).first()
                equipamento = DispositivosEquipamentos(serial=form.serial.data.upper(), hostname=form.hostname.data.upper(), patrimonio=form.patrimonio.data.upper(), modelo=form.modelo.data.upper(
                ), processador=form.processador.data.upper(), fabricante=form.fabricante.data.upper(), idArea=area.id, idSite=int(form.idSite.data), idTipo=tipoDispositivo.id)
                db.session.add(equipamento)
                db.session.commit()
            except Exception as e:
                print(f'Error: {e}')
                db.session.flush()
                db.session.rollback()

            if equipamento:
                try:
                    pa = db.session.query(PontoAtendimentos).filter(and_(
                        PontoAtendimentos.descricao == form.pa.data, PontoAtendimentos.idSite == int(form.idSite.data))).first()

                    data_e_hora_atuais = datetime.now()
                    fuso_horario = timezone('America/Sao_Paulo')

app/templates/equipamentos/create_equipamento.html
{% extends "layout2.html" %}
{% block content %}
  <header>
    <div class="jumbotron jumbotron-fluid mt-4">
      <div class="container">
        <h1 class="display-4"><i class="fa-solid fa-house-laptop"></i> {{legenda}}</h1>
        <p class="lead">{{descricao}}</p>
      </div>
    </div>
  </header>
  <div class="content-section mt-4">
    <form method="POST" action="">
      {{ form.hidden_tag() }}
      <fieldset class="form-group">
        <legend class="border-bottom mb-4">Formulario para cadastrar novo equipamento inventário</legend>
        <div class="form-row">
          <div class="col-6">
            {{ form.modelo.label(class='form-control-label') }}
            {% if form.modelo.errors %}
              {{ form.modelo(class='form-control form-control-lg is-invalid')}}
              <div class="invalid-feedback">
                {% for error in form.modelo.errors %}
                  <span>{{ error }}</span>
                {% endfor %}
              </div>
            {% else %}
              {{ form.modelo(class='form-control form-control-lg', placeholder='Ex.: OPTIPLEX 3070')}}
            {% endif %}
          </div>
          <div class="col-6">
            {{ form.serial.label(class='form-control-label') }}
            {% if form.serial.errors %}
              {{ form.serial(class='form-control form-control-lg is-invalid')}}
              <div class="invalid-feedback">
                {% for error in form.serial.errors %}
                  <span>{{ error }}</span>
                {% endfor %}
              </div>
            {% else %}
              {{ form.serial(class='form-control form-control-lg',placeholder='Ex.: XTPOQ1V1')}}
            {% endif %}
          </div>
        </div>
        <div class="form-row mt-4">
          <div class="col-6">
            {{ form.patrimonio.label(class='form-control-label') }}
            {% if form.patrimonio.errors %}
              {{ form.patrimonio(class='form-control form-control-lg is-invalid')}}
              <div class="invalid-feedback">
                {% for error in form.patrimonio.errors %}
                  <span>{{ error }}</span>
                {% endfor %}
              </div>
            {% else %}
              {{ form.patrimonio(class='form-control form-control-lg', placeholder='Ex.: MSG00000001234')}}
            {% endif %}
          </div>
          <div class="col-6">
            {{ form.hostname.label(class='form-control-label') }}
            {% if form.hostname.errors %}
              {{ form.hostname(class='form-control form-control-lg is-invalid')}}
              <div class="invalid-feedback">
                {% for error in form.hostname.errors %}
                  <span>{{ error }}</span>
                {% endfor %}
              </div>
            {% else %}
              {{ form.hostname(class='form-control form-control-lg', placeholder='Ex.: PBR001150-M1234')}}
            {% endif %}
          </div>
        </div>
        <div class="form-row mt-4">
          <div class="col-6">
            {{ form.processador.label(class='form-control-label') }}
            {% if form.processador.errors %}
              {{ form.processador(class='form-control form-control-lg is-invalid')}}
              <div class="invalid-feedback">
                {% for error in form.processador.errors %}
                  <span>{{ error }}</span>
                {% endfor %}
              </div>
            {% else %}
              {{ form.processador(class='form-control form-control-lg',placeholder='Ex.: I3, I5, I7')}}
            {% endif %}
          </div>
          <div class="col-6">
            {{ form.fabricante.label(class='form-control-label') }}
            {% if form.fabricante.errors %}
              {{ form.fabricante(class='form-control form-control-lg is-invalid')}}
              <div class="invalid-feedback">
                {% for error in form.fabricante.errors %}
                  <span>{{ error }}</span>
                {% endfor %}
              </div>
            {% else %}
              {{ form.fabricante(class='form-control form-control-lg', placeholder='Ex.: Dell, Lenovo')}}
            {% endif %}
          </div>
        </div>
        <div class="form-row mt-4">
          <div class="col-6">
            {{form.pa.label(class="form-group mr-2")}}
            {% if form.pa.errors %}
              {{form.pa(class='custom-select mr-sm-2 is-invalid')}}
              <div class="invalid-feedback">
                {% for error in form.pa.errors %}
                  <span>{{ error }}</span>
                {% endfor %}
              </div>
            {% else %}
              {{ form.pa(class='custom-select')}}
            {% endif %}
          </div>
          <div class="col-6">
            {{form.tipoDispositivo.label(class='form-group mr-2')}}
            {{form.tipoDispositivo(class='custom-select mr-sm-2')}}
          </div>
          <!-- <div class="form-check form-check-inlinee mt-4">
            {% for i in form.tipoDispositivo %}
              {{i}}
              {{i.label(class='form-check-label')}}
              &nbsp;&nbsp;
            {% endfor %}
          </div> -->
          
        </div>
        <div class="form-group mt-4">
          {{ form.submit(class='btn btn-outline-primary')}}
          <a href="{{url_for('equipamento.consultaInventario', idSite=idSite)}}" class="btn btn-outline-danger ml-3">Cancelar</a>
        </div>
      </fieldset>
    </form>
  </div>
{% endblock content %}

app/templates/equipamentos/create_tipoEquipamento.html
{% extends "layout2.html" %}
{% block content %}
  <header>
    <div class="jumbotron jumbotron-fluid mt-4">
      <div class="container">
        <h1 class="display-4"><i class="fa-regular fa-keyboard"></i> {{legenda}}</h1>
        <p class="lead">{{descricao}}</p>
      </div>
    </div>
  </header>
  <div class="content-section mt-4">
    <form method="POST" action="">
      {{ form.hidden_tag() }}
      <fieldset class="form-group">
        <div class="form-row">
          <div class="form-group col-md-8">
            {{ form.nome.label(class='form-control-label') }} 
            {% if form.nome.errors %} 
              {{ form.nome(class='form-control form-control-lg is-invalid')}}
              <div class="invalid-feedback">
                {% for error in form.nome.errors %}
                  <span>{{ error }}</span>
                {% endfor %}
              </div>
            {% else %} 
              {{ form.nome(class='form-control form-control-lg', placeholder='Ex.: Notebook - Desktop, Teclados, etc..')}}
            {% endif %}
          </div>
          <div class="form-group col-md-4">
            {{form.site.label(class='form-control-label')}}
            {% if form.site.errors %} 
            {{ form.site(class='form-control form-control-lg is-invalid')}}
              <div class="invalid-feedback">
                {% for error in form.site.errors %}
                  <span>{{ error }}</span>
                {% endfor %}
              </div>
            {% else %} 
              {{form.site(class='form-control form-control-lg')}}
            {% endif %}
          </div>
        </div>
        <div class="form-group mt-4">
          {{ form.submit(class='btn btn-outline-primary')}}
          <a href="{{url_for('equipamento.equipamentoView')}}" class="btn btn-outline-danger ml-3">Cancelar</a>          
        </div>
      </fieldset>
    </form>
  </div>
{% endblock content %}

app/templates/equipamentos/inventario.html
{% extends 'layout2.html' %} {% block content %}
<header>
  <div class="jumbotron jumbotron-fluid mt-4">
    <div class="container">
      <h1 class="display-4"><i class="fa-solid fa-computer"></i> {{legenda}}</h1>
      <p class="lead"> {{descricao}} </p>
    </div>
  </div>
  <!-- <h2 class="my-3">Listagem</h2> -->
  <form
    action="{{url_for('equipamento.inventario')}}"
    method="POST"
    class="ml-3 mb-4"
  >
    <div class="form-group">
      <div class="row">
        {{form.consulta(class='form-control col-md-5', placeholder='Digita aqui a consulta')}}
        {{form.selection(class='form-control col-md-2 ml-3')}}
        <button type="submit" class="btn btn-success ml-4">
          <i class="fa-solid fa-magnifying-glass"></i> Consultar
        </button>
        <a
          class="btn btn-primary ml-3"
          href="{{url_for('equipamento.novo_equipamento', idSite=idSite)}}"
          role="button"
          ><i class="fa-solid fa-desktop"></i> Novo</a
        >
        <a class="btn btn-warning ml-3" href=" " role="button"
          ><i class="fa-regular fa-file-pdf"></i> PDF</a
        >
      </div>
    </div>
  </form>
</header>
<main>
  <table class="table table-hover text-center">
    <thead>
      <tr class="table-secondary">
        <!-- <th scope="col"><a href="#">Id</a></th> -->
        <th scope="col"><a href="#">Serial</a></th>
        <th scope="col"><a href="#">Patrimônio</a></th>
        <th scope="col"><a href="#">Hostname</a></th>
        <th scope="col"><a href="#">Local</a></th>
        <th scope="col"><a href="#">Tipo Equipamento</a></th>
        <th scope="col">Ação</th>
      </tr>
    </thead>
    <tbody>
      {% for computador in computadores%}
      <tr>
        <!-- <th scope="row">{{computador.id}}</th> -->
        <td>{{computador.serial}}</td>
        <td>{{computador.patrimonio}}</td>
        <td>{{computador.hostname}}</td>
        <td>{{computador.descricao}}</td>
        <td>{{computador.nome}}</td>
        {% if computador %}
        <td>
          <a href="" onclick="editarInventario('{{computador.id}}','{{idSite}}')" role="button" class="btn btn-danger ml-3" data-toggle="modal" data-target="#editarInventario"
            ><i class="fa-solid fa-pen-to-square"></i
          ></a>
        </td>
        {% endif %}
      </tr>
      {% endfor %}
    </tbody>
  </table>
</main>

<!-- Modal -->
<div
  class="modal fade"  id="editarInventario"  tabindex="-1"  role="dialog"  aria-labelledby="editarInventarioTitle"  aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">O que deseja fazer?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <input type="hidden" name="idDispositivo" id="idDispositivo" />
        <input type="hidden" name="idSite" id="idSite" />
        <div class="form-row">
          <div class="col-md-3">
            <a class="btn btn-primary ml-1" onclick="mudarLayout()" role="button"><i class="fa-solid fa-arrows-rotate"></i> MD.Layout</a>
          </div>
          <div class="col-md-3">
            <a class="btn btn-warning ml-2" onclick="editarDadosEquipamentoInventario()" role="button"><i class="fa-solid fa-pen-to-square"></i> Atualizar</a>
          </div>
          <div class="col-md-3">
            <a class="btn btn-danger ml-2" onclick="moverDescarte()" role="button"><i class="fa-solid fa-trash-can"></i> Descarte</a>
          </div>
          <div class="col-md-3">
            <a class="btn btn-primary ml-2" onclick="moverEstoque()" role="button"><i class="fa-solid fa-boxes-stacked"></i> MV.Estoque</a>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">
          Fechar
        </button>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

app/templates/equipamentos/inventario_view.html
{% extends 'layout2.html' %}
{% block content %}
  <header>
    <div class="jumbotron jumbotron-fluid mt-4">
      <div class="container">
        <h1 class="display-4"><i class="fa-solid fa-clipboard-list"></i> {{legenda}}</h1>
        <p class="lead">{{descricao}}</p>
      </div>
    </div>
    <!-- <h2 class="my-3">Listagem</h2> -->
    <form action="" method="POST" class="ml-3 mb-4">
      <div class="form-group">
        <div class="row">
          {{form.consulta(class='form-control col-md-5', placeholder='Digita aqui a consulta')}}
          {{form.selection(class='form-control col-md-2 ml-3')}}
          <button type="submit" class="btn btn-success ml-4"><i class="fa-solid fa-magnifying-glass"></i> Consultar</button>
          <a class="btn btn-warning ml-3" href=" " role="button"><i class="fa-regular fa-file-pdf"></i> PDF</a>
        </div>
      </div>
    </form>
  </header>
  <main>
    <table class="table table-hover text-center">
      <thead>
        <tr class="table-secondary">
          <th scope="col"><a href="#">Id</a></th>
          <th scope="col"><a href="#">Local do Inventário</a></th>
          <th scope="col">Ação</th>
        </tr>
      </thead>
      <tbody>
        {% for site in sites%}
        <tr>
          <th scope="row">{{site.id}}</th>
          <td>{{site.nome}}</td>
          {% if site %}
            <!-- <td><a href="" onclick="editarInventario('{{site.id}}')" role="button" class="btn btn-danger ml-3" data-toggle="modal" data-target="#editarInventario"><i class="fa-solid fa-pen-to-square"></i></a></td> -->
            <td><a class="btn btn-info" href="{{url_for('equipamento.consultaInventario', idSite=site.id)}}" role="button"><i class="fa-solid fa-pen-to-square"></i> Acessar</a></td>
          {% endif %}
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </main>

  <!-- Modal -->
  <div class="modal fade" id="editarInventario" tabindex="-1" role="dialog" aria-labelledby="editarInventarioTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLongTitle">O que deseja fazer?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <input type="hidden" name="id_inventario" id="id_inventario">
          <div class="form-row">
            <div class="col-md-3">
              <a href="" class="btn btn-primary ml-3" onclick="window.location = updateURLUser()" role="button"><i class="fa-solid fa-arrows-rotate"></i> M.Layout</a>
            </div>
            <div class="col-md-3">
              <a href="" class="btn btn-primary ml-3" onclick="trocarSenhaURLUser()" role="button"><i class="fa-solid fa-boxes-stacked"></i> M.Extoque</a>
            </div>
            <div class="col-md-3">
              <a class="btn btn-warning ml-3" onclick="ediatarDadosEquipamentoInventario()" role="button"><i class="fa-solid fa-pen-to-square"></i> Atualizar</a>
            </div>
            <div class="col-md-3">
              <a href="" class="btn btn-danger ml-3" onclick="trocarSenhaURLUser()" role="button"><i class="fa-solid fa-trash-can"></i> Descarte</a>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

app/templates/equipamentos/mudanca_layout.html
{% extends 'layout2.html' %}
{% block content %}
<header>
  <div class="jumbotron jumbotron-fluid mt-4">
    <div class="container">
      <h1 class="display-4"><i class="fa-solid fa-clipboard-list"></i> {{legenda}}</h1>
      <p class="lead">{{descricao}}</p>
    </div>
  </div>
</header>
<main>
  <form action="" method="POST">
    {{ form.hidden_tag() }}
    <div class="form-row">
      <div class="col">
        {{ form.serial.label(class='form-control-label') }} 
        {% if form.serial.errors %} 
          {{ form.serial(class='form-control form-control-lg is-invalid')}}
          <div class="invalid-feedback">
            {% for error in form.serial.errors %}
              <span>{{ error }}</span>
            {% endfor %}
          </div>
        {% else %} 
          {{ form.serial(class='form-control form-control-lg', disabled=true)}}
        {% endif %}
      </div>
      <div class="col">
        {{ form.patrimonio.label(class='form-control-label') }} 
        {% if form.patrimonio.errors %} 
          {{ form.patrimonio(class='form-control form-control-lg is-invalid')}}
          <div class="invalid-feedback">
            {% for error in form.patrimonio.errors %}
              <span>{{ error }}</span>
            {% endfor %}
          </div>
        {% else %} 
          {{ form.patrimonio(class='form-control form-control-lg', disabled=true)}}
        {% endif %}
      </div>
      <div class="col">
        {{ form.modelo.label(class='form-control-label') }} 
        {% if form.modelo.errors %} 
          {{ form.modelo(class='form-control form-control-lg is-invalid')}}
          <div class="invalid-feedback">
            {% for error in form.modelo.errors %}
              <span>{{ error }}</span>
            {% endfor %}
          </div>
        {% else %} 
          {{ form.modelo(class='form-control form-control-lg', disabled=true)}}
        {% endif %}
      </div>
      <div class="col">
        {{ form.tipo.label(class='form-control-label') }} 
        {% if form.tipo.errors %} 
          {{ form.tipo(class='form-control form-control-lg is-invalid')}}
          <div class="invalid-feedback">
            {% for error in form.tipo.errors %}
              <span>{{ error }}</span>
            {% endfor %}
          </div>
        {% else %} 
          {{ form.tipo(class='form-control form-control-lg', disabled=true)}}
        {% endif %}
      </div>
    </div>
    <div class="form-row mt-4">
      <div class="col">
        {{ form.de.label(class='form-control-label') }} 
        {% if form.de.errors %} 
          {{ form.de(class='form-control form-control-lg is-invalid')}}
          <div class="invalid-feedback">
            {% for error in form.de.errors %}
              <span>{{ error }}</span>
            {% endfor %}
          </div>
        {% else %} 
          {{ form.de(class='form-control form-control-lg', placeholder='Ex.: TA-BA-F1-P1', disabled=true)}}
        {% endif %}
      </div>
      <div class="col">
        {{ form.para.label(class='form-control-label') }} 
        {% if form.para.errors %} 
          {{ form.para(class='form-control form-control-lg is-invalid')}}
          <div class="invalid-feedback">
            {% for error in form.para.errors %}
              <sparan>{{ error }}</sparan>
            {% endfor %}
          </div>
        {% else %} 
          {{ form.para(class='form-control form-control-lg', placeholder='Ex.: TA-BA-F1-P2')}}
        {% endif %}
      </div>
    </div>
    <div class="form-row mt-4">
      <div class="col">
        {{form.submit(class='btn btn-outline-primary')}}
        <a href="{{url_for('equipamento.consultaInventario', idSite=idSite)}}" class="btn btn-outline-danger ml-3"><i class="fa-solid fa-xmark"></i> Cancelar</a>   
      </div>
    </div>
  </form>
</main>

{% endblock content %}