app/controllers/main/routes.py
from flask import render_template, flash, redirect, url_for, Blueprint, request, abort
from app.controllers.main.form import (
    SiteForm, LocalAtendimento, SiteUpdateForm, UpdateLocal, AreaForm, localViewForm, AreaViewForm, ConsultaSiteForm)
from flask_login import current_user, login_required
from app.models.bdMonitora import Enderecos, Sites, PontoAtendimentos, Areas
from app import db
from sqlalchemy import exc, and_
from app.controllers.equipamento.monitora import Monitora
from datetime import date, datetime


main = Blueprint('main', __name__)


@main.route('/')
@main.route('/home')
@main.route('/monitora')
def home():
    # print(current_user.id)
    monitora = Monitora()
    return render_template('main/home.html', title='Home', local='São Carlos', computador=monitora.computadoresView())


@main.route('/site')
@login_required
def site():
    # print(current_user.permissoes)
    form = ConsultaSiteForm()
    if (current_user.permissoes[0].leitura or current_user.permissoes[0].escrita) and (current_user.permissoes[0].leitura or current_user.permissoes[0].escrita) and current_user.ativo:
        sites = db.session.query(Sites.id, Sites.nome, Enderecos.rua, Enderecos.cep, Enderecos.cidade).join(
            Sites, Enderecos.id == Sites.id).all()
        return render_template('main/site.html', title='Site', sites=sites, form=form)
    else:
        abort(403)

@main.route('/consultaSite', methods=['POST'])
@login_required
def consultaSite():
    if (current_user.permissoes[0].leitura or current_user.permissoes[0].escrita) and current_user.ativo:
        form = ConsultaSiteForm()
        if form.validate_on_submit():
            consulta = '%'+form.consulta.data+'%'
            selection = form.selection.data
            if selection == 'Site':
                sites = db.session.query(Sites.id, Sites.nome, Enderecos.rua, Enderecos.cep, Enderecos.cidade).join(Sites, Enderecos.id == Sites.id).filter(Sites.nome.like(consulta)).all()
            elif selection == 'Cidade':
                sites = db.session.query(Sites.id, Sites.nome, Enderecos.rua, Enderecos.cep, Enderecos.cidade).join(Sites, Enderecos.id == Sites.id).filter(Enderecos.cidade.like(consulta)).all()
            elif selection == 'Cep':
                 sites = db.session.query(Sites.id, Sites.nome, Enderecos.rua, Enderecos.cep, Enderecos.cidade).join(Sites, Enderecos.id == Sites.id).filter(Enderecos.cep.like(consulta)).all()
            else:
                sites = db.session.query(Sites.id, Sites.nome, Enderecos.rua, Enderecos.cep, Enderecos.cidade).join(Sites, Enderecos.id == Sites.id).all()
            return render_template('main/site.html', title='Site', sites=sites, form=form)
        else:
            flash('Erro, verificar dados informados ', 'danger')
            sites = db.session.query(Sites.id, Sites.nome, Enderecos.rua, Enderecos.cep, Enderecos.cidade).join(Sites, Enderecos.id == Sites.id).all()
            return render_template('main/site.html', title='Site', sites=sites, form=form)
    else:
        abort(403)

@main.route('/site/new', methods=['GET', 'POST'])
@login_required
def registrar_site():
    if (current_user.permissoes[0].leitura or current_user.permissoes[0].escrita) and current_user.ativo:
        form = SiteForm()
        if form.validate_on_submit():
            endereco = Enderecos(cidade=form.cidade.data.title(), rua=form.rua.data.title(), cep=form.cep.data)
            db.session.add(endereco)
            db.session.commit()
            site = Sites(nome=form.nome.data.title(), idEndereco=endereco.id)
            db.session.add(site)
            db.session.commit()
            areas = ['Estoque', 'Inventario', 'Descarte']
            for area in areas:
                a = Areas(nome=area, site=[site])
                db.session.add(a)
                db.session.commit()

            flash('Site Cadastrado com sucesso!', 'success')
            return redirect(url_for('main.site'))
        return render_template('main/registrar_site.html', title='Registrar Site', form=form)
    else:
        abort(403)


@main.route('/site/<int:id_site>/update', methods=['GET', 'POST'])
@login_required
def update_site(id_site):
    if (current_user.permissoes[0].leitura or current_user.permissoes[0].escrita) and current_user.ativo:
        try:
            endereco = Enderecos.query.get_or_404(id_site)
            site = Sites.query.filter_by(idEndereco=endereco.id).first_or_404()
        except Exception as e:
            print(f'Erro ao consultar: {e}')
        form = SiteUpdateForm()
        if form.validate_on_submit():
            endereco.rua = form.rua.data.title()
            endereco.cep = form.cep.data
            endereco.cidade = form.cidade.data.title()
            site.nome = form.nome.data.title()
            db.session.commit()
            flash('Dados atualizados com sucesso', 'success')
            return redirect(url_for('main.site'))
        elif request.method == 'GET':
            form.rua.data = endereco.rua
            form.cep.data = endereco.cep
            form.cidade.data = endereco.cidade
            form.nome.data = site.nome
        return render_template('main/update_site.html', title='Update Site', legenda='Editar Site', id_site=id_site, form=form)
    else:
        abort(403)


@main.route('/site/delete', methods=['POST'])
@login_required
def delete_site():
    if (current_user.permissoes[0].leitura or current_user.permissoes[0].escrita) and current_user.ativo:
        id_site = request.form.get('id_site')
        endereco = Enderecos.query.get_or_404(id_site)
        site = Sites.query.filter_by(idEndereco=endereco.id).first_or_404()
        if site.id != 1:
            db.session.delete(endereco)
            db.session.delete(site)
            db.session.commit()
            flash('Site removido conforme solicitado', 'success')
        else:
            flash('Restrição de segurança - Site não pode ser removido', 'danger')
        return redirect(url_for('main.site'))
    else:
        abort(403)


@main.route('/local/<int:idSite>/consulta', methods=['GET', 'POST'])
@login_required
def localizarPA(idSite):
    if (current_user.permissoes[0].leitura or current_user.permissoes[0].escrita) and current_user.ativo:
        print(f'Site ID: {idSite}')
        locais = db.session.query(PontoAtendimentos.id, PontoAtendimentos.descricao, Sites.nome).join(
            PontoAtendimentos, Sites.id == PontoAtendimentos.idSite).filter(Sites.id == idSite).all()
        if locais:
            return render_template('main/local.html', title='Ponto Atendimento', locais=locais, idSite=idSite, legenda='Pontos de  Atendimentos', descricao=f'Relação de todos as P.A.s cadastradas no Site: {locais[0].nome}')
        else:
            return render_template('main/local.html', title='Ponto Atendimento', locais=locais, idSite=idSite, legenda='Pontos de  Atendimentos', descricao='Não existe Ponto atendimento para Local selecionado.')
    else:
        abort(403)


@main.route('/local/view')
@login_required
def localView():
    if (current_user.permissoes[0].leitura or current_user.permissoes[0].escrita) and current_user.ativo:
        form = localViewForm()
        try:
            sites = db.session.query(Sites).all()
        except Exception as e:
            print(f'Error: {e}')
        return render_template('main/local_view.html', title='Ponto Atendimento', legenda='Pontos de Atendimentos', descricao='Seleciono o Site que deseja acessar', sites=sites, form=form)
    else:
        abort(403)


# @main.route('/local/registrarLocal', methods=['GET', 'POST'])
@main.route('/local/<int:idSite>/novo', methods=['GET', 'POST'])
@login_required
def registrarLocal(idSite):
    if (current_user.permissoes[0].leitura or current_user.permissoes[0].escrita) and current_user.ativo:
        form = LocalAtendimento()
        if form.validate_on_submit():
            site = Sites.query.filter_by(nome=form.localSelect.data).first()
            if site:
                local = PontoAtendimentos(descricao=form.localPa.data.upper(), idSite=site.id)
                db.session.add(local)
                db.session.commit()
                flash('Ponto de atendimento cadastrado com sucesso', 'success')
                return redirect(url_for('main.localizarPA', idSite=idSite))
            else:
                flash('Ponto de atendimento cadastrado com sucesso', 'danger')
                return redirect(url_for('main.registrarPa'))
        elif request.method == 'GET':
            try:
                site = Sites.query.get(idSite)
            except Exception as e:
                print(f'Error: {e}')
            form.localSelect.choices = [site.nome]
            return render_template('main/create_ponto_atendimento.html', title='Novo Ponto Atendimento', legenda='Ponto Atendento (P.A)', descricao=f'Preencha a descrição da P.A para realizar o cadastro no site: {site.nome}', form=form, idSite=idSite)

    else:
        abort(403)


@main.route('/local/<int:id_local>/update', methods=['GET', 'POST'])
@login_required
def updateLocal(id_local):
    if (current_user.permissoes[0].leitura or current_user.permissoes[0].escrita) and current_user.ativo:
        form = UpdateLocal()
        try:
            localForm = db.session.query(PontoAtendimentos.descricao, PontoAtendimentos.idSite, PontoAtendimentos.id, Sites.nome).join(
                Sites, Sites.id == PontoAtendimentos.idSite).filter(PontoAtendimentos.id == id_local).first_or_404()
            # print(local)
            # precisa verificar a consulta para atualizar local e o site
        except Exception as e:
            print(f'Erro ao realizar consulta{e}')
            abort(404)
        if form.validate_on_submit():
            try:
                local = PontoAtendimentos.query.get_or_404(id_local)
                site = Sites.query.filter(
                    Sites.nome == form.localSelect.data).first_or_404()
            except Exception as e:

app/templates/main/area_view.html
{% extends 'layout2.html' %}
{% block content %}
<header>
  <div class="jumbotron jumbotron-fluid mt-4">
    <div class="container">
      <h1 class="display-4"><i class="fa-solid fa-clipboard-list"></i> {{legenda}}</h1>
      <p class="lead">{{descricao}}</p>
    </div>
  </div>
  <!-- <h2 class="my-3">Listagem</h2> -->
  <form action="" method="POST" class="ml-3 mb-4">
    <div class="form-group">
      <div class="row">
        {{form.consulta(class='form-control col-md-5', placeholder='Digita aqui a consulta')}}
        {{form.selection(class='form-control col-md-2 ml-3')}}
        <button type="submit" class="btn btn-success ml-4"><i class="fa-solid fa-magnifying-glass"></i> Consultar</button>
        <a class="btn btn-warning ml-3" href=" " role="button"><i class="fa-regular fa-file-pdf"></i> PDF</a>
      </div>
    </div>
  </form>
</header>
<main>
  <table class="table table-hover text-center">
    <thead>
      <tr class="table-secondary">
        <th scope="col"><a href="#">Id</a></th>
        <th scope="col"><a href="#">Local do Site</a></th>
        <th scope="col">Ação</th>
      </tr>
    </thead>
    <tbody>
      {% for site in sites%}
      <tr>
        <th scope="row">{{site.id}}</th>
        <td>{{site.nome}}</td>
        {% if site %}
          <!-- <td><a href="" onclick="editarInventario('{{site.id}}')" role="button" class="btn btn-danger ml-3" data-toggle="modal" data-target="#editarInventario"><i class="fa-solid fa-pen-to-square"></i></a></td> -->
          <td><a class="btn btn-info" href="{{url_for('main.areaConsula', idSite=site.id)}}" role="button"><i class="fa-solid fa-pen-to-square"></i> Acessar</a></td>
        {% endif %}
      </tr>
      {% endfor %}
    </tbody>
  </table>
</main>

<!-- Modal -->
<div class="modal fade" id="editarInventario" tabindex="-1" role="dialog" aria-labelledby="editarInventarioTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">O que deseja fazer?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <input type="hidden" name="id_inventario" id="id_inventario">
        <div class="form-row">
          <div class="col-md-3">
            <a href="" class="btn btn-primary ml-3" onclick="window.location = updateURLUser()" role="button"><i class="fa-solid fa-arrows-rotate"></i> M.Layout</a>
          </div>
          <div class="col-md-3">
            <a href="" class="btn btn-primary ml-3" onclick="trocarSenhaURLUser()" role="button"><i class="fa-solid fa-boxes-stacked"></i> M.Extoque</a>
          </div>
          <div class="col-md-3">
            <a class="btn btn-warning ml-3" onclick="ediatarDadosEquipamentoInventario()" role="button"><i class="fa-solid fa-pen-to-square"></i> Atualizar</a>
          </div>
          <div class="col-md-3">
            <a href="" class="btn btn-danger ml-3" onclick="trocarSenhaURLUser()" role="button"><i class="fa-solid fa-trash-can"></i> Descarte</a>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

app/templates/main/create_area.html
{% extends "layout2.html" %}
{% block content %}
  <header>
    <div class="jumbotron jumbotron-fluid mt-4">
      <div class="container">
        <h1 class="display-4"><i class="fa-solid fa-warehouse"></i> {{descricao}}</h1>
        <p class="lead">Preenchar todos os campos para cadastrar nova área no site.</p>
      </div>
    </div>
  </header>
  <div class="content-section mt-4">
    <form method="POST" action="">
      {{ form.hidden_tag() }}
      <fieldset class="form-group">
        <!-- <legend class="border-bottom mb-4">Cadastrar Novo Equipamento Site</legend> -->
        <div class="form-row">
          <div class="form-group col-md-6">
            {{ form.area.label(class='form-control-label') }} 
            {% if form.area.errors %} 
              {{ form.area(class='form-control form-control-lg is-invalid')}}
              <div class="invalid-feedback">
                {% for error in form.area.errors %}
                  <span>{{ error }}</span>
                {% endfor %}
              </div>
            {% else %} 
              {{ form.area(class='form-control form-control-lg', placeholder='Ex.: Estoque, Inventário, Descarte....')}}
            {% endif %}
          </div>
          <div class="form-group col-md-6">
            {{form.localSelect.label(class="form-group mr-2")}}
            {% if form.localSelect.errors %}
              {{ form.localSelect(class='custom-select mr-sm-2 is-invalid')}}
              <div class="invalid-feedback">
                {% for error in form.localSelect.errors %}
                  <span>{{ error }}</span>
                {% endfor %}
              </div>
            {% else %}
              {{form.localSelect(class='custom-select mr-sm-2')}}
            {% endif %}
          </div>
        </div>
        <div class="form-group mt-4">
          {{ form.submit(class='btn btn-outline-primary')}}
          <a href="{{url_for('main.areaView')}}" class="btn btn-outline-danger ml-3">Cancelar</a>
          
        </div>
      </fieldset>
    </form>
  </div>
{% endblock content %}

app/templates/main/create_ponto_atendimento.html
{% extends "layout2.html" %}
{% block content %}
  <header>
    <div class="jumbotron jumbotron-fluid mt-4">
      <div class="container">
        <h1 class="display-4"><i class="fa-solid fa-table-columns"></i> {{legenda}}</h1>
        <p class="lead">{{descricao}}</p>
      </div>
    </div>
  </header>
  <div class="content-section mt-4">
    <form method="POST" action="">
      {{ form.hidden_tag() }}
      <fieldset class="form-group">
        <!-- <legend class="border-bottom mb-4">Cadastrar Novo Equipamento Site</legend> -->
        <div class="form-row">
          <div class="form-group col-md-6">
            {{ form.localPa.label(class='form-control-label') }} {% if
            form.localPa.errors %} {{ form.localPa(class='form-control form-control-lg
            is-invalid')}}
            <div class="invalid-feedback">
              {% for error in form.localPa.errors %}
                <span>{{ error }}</span>
              {% endfor %}
            </div>
            {% else %} 
              {{ form.localPa(class='form-control form-control-lg', placeholder='Ex.: TA-F1-BA-P1')}}
            {% endif %}
          </div>
          <div class="form-group col-md-6">
            {{form.localSelect.label(class="form-group mr-2")}}
            {{form.localSelect(class='custom-select mr-sm-2')}}
          </div>
        </div>
        <div class="form-group mt-4">
          {{ form.submit(class='btn btn-outline-primary')}}
          <a href="{{url_for('main.localizarPA', idSite=idSite)}}" class="btn btn-outline-danger ml-3">Cancelar</a>
          
        </div>
      </fieldset>
    </form>
  </div>
{% endblock content %}

app/templates/main/home.html
{% extends 'layout.html' %}

{% block content %}
<div class="home">
   
    <main role="main">

        <!-- Main jumbotron for a primary marketing message or call to action -->
        <div class="jumbotron">
            <div class="container">
                {% with messages = get_flashed_messages(with_categories=true)%}
                    {% if messages %}
                        {% for category, message in messages %}
                            <div class="alert alert-{{category}}">
                                {{message}}
                            </div>
                        {% endfor %}
                    {%endif%}
                {%endwith%}
                <h1 class="display-3 monitora"><i class="fa-solid fa-binoculars"></i> Monitora</h1>
                <p class="monitoraInfo">Para atualizar informações dos computadores no site selecione o botão atualizar e aguarde.</p>
                <p><a class="btn btn-primary btn-lg" href="{{url_for('main.atualizarComputadorSite')}}" role="button">Atualizar &raquo;</a></p>
            </div>
        </div>

        <div class="container">
            <!-- Example row of columns -->
            <div class="row">
                <div class="col-md-4">
                    <img class="dashimg" src="{{url_for('static', filename='img/ok.png')}}" alt="">
                    <spam class="conectado"> Conectado</spam>
                    <p class="dashdispositivo">Dispositivo(s):<spam class="dashqtd"> {{computador.conectado}}</spam></p>
                    <p><a class="btn btn-secondary detalhe" href="{{url_for('equipamento.detalhe', tipo_relatorio='Conectado')}}" role="button">Ver delalhe &raquo;</a></p>
                </div>
                <div class="col-md-4">
                    <img class="dashimg" src="{{url_for('static', filename='img/erro.png')}}" alt="">
                    <span class="desconectado">Desconectado</span>
                    <p class="dashdispositivo">Dispositivo(s):<spam class="dashqtd"> {{computador.desconectado}}</spam></p>
                    <p><a class="btn btn-secondary detalhe" href="{{url_for('equipamento.detalhe', tipo_relatorio='Desconectado')}}" role="button">Ver delalhe&raquo;</a></p>
                </div>
                <div class="col-md-4">
                    <img class="dashimg" src="{{url_for('static', filename='img/Atenção.png')}}" alt="">
                    <spam class="atencao">Atenção</spam>
                    <p class="dashdispositivo">Dispositivo(s):<spam class="dashqtd"> {{computador.atencao}}</spam></p>
                    <p><a class="btn btn-secondary detalhe" href="{{url_for('equipamento.detalhe', tipo_relatorio='Atenção')}}" role="button">Ver delalhe &raquo;</a></p>
                </div>
            </div>
            <div class="row dataHora">
                <div class="col-md-6">
                    <p class="dashData">Atualizado:<spam class="data"> {{computador.data}}</spam></p>
                </div>
                <div class="col-md-6">
                    <p class="dashHora">Hora:<spam class="data"> {{computador.hora}}</spam></p>
                </div>
            </div>
        </div>
    </main>
</div>
{% endblock %}

app/templates/main/listar_area.html
{% extends 'layout2.html' %}
{% block content %}
  <header>
    <div class="jumbotron jumbotron-fluid mt-4">
      <div class="container">
        <h1 class="display-4"><i class="fa-solid fa-warehouse"></i> {{legenda}}</h1>
        <p class="lead">{{descricao}}</p>
      </div>
    </div>
    <form action="#" class="ml-3 mb-4">
      <div class="form-group">
        <div class="row">
          <input type="text" class="form-control col-md-5" name="consulta" placeholder="Digita aqui a consulta"/>
          <select class="form-control col-md-2 ml-3" name="campo" id="">
            <option value="area">Área</option>
            <option value="LocalArea">Local Área</option>
          </select>
          <button type="submit" class="btn btn-success ml-4"><i class="fa-solid fa-magnifying-glass"></i> Consultar</button>
          <!-- <a class="btn btn-primary ml-3" href="{{url_for('main.area', idSite=idSite)}}" role="button"><i class="fa-solid fa-plus"></i> Novo</a> -->
          <a class="btn btn-warning ml-3" href=" " role="button"><i class="fa-regular fa-file-pdf"></i> PDF</a>
        </div>
      </div>
    </form>
  </header>
  <main>
    <table class="table table-hover text-center">
      <thead>
        <tr class="table-secondary">
          <th scope="col"><a href="#">Id</a></th>
          <th scope="col"><a href="#">Nome Área</a></th>
          <th scope="col"><a href="#">Local Área</a></th>
          <th scope="col">Ação</th>
        </tr>
      </thead>
      <tbody>
        {% for area in areas%}
          <tr>
            <th scope="row">{{area.id}}</th>
            <td>{{area.nome}}</td>
            <td>{{area.site}}</td>
            <td><a class="btn btn-info" href="#" role="button"><i class="fa-solid fa-pen-to-square"></i> Editar</a></td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </main>
{% endblock content %}

app/templates/main/local.html
{% extends 'layout2.html' %}
{% block content %}
  <header>
    <div class="jumbotron jumbotron-fluid mt-4">
      <div class="container">
        <h1 class="display-4"><i class="fa-solid fa-table-columns"></i> {{legenda}}</h1>
        <p class="lead">{{descricao}}</p>
      </div>
    </div>
    <form action="#" class="ml-3 mb-4">
      <div class="form-group">
        <div class="row">
          <input type="text" class="form-control col-md-5" name="consulta" placeholder="Digita aqui a consulta"/>
          <select class="form-control col-md-2 ml-3" name="campo" id="">
            <option value="pa">Local</option>
            <option value="site">Site</option>
          </select>
          <button type="submit" class="btn btn-success ml-4"><i class="fa-solid fa-magnifying-glass"></i> Consultar</button>
          <a class="btn btn-primary ml-3" href="{{url_for('main.registrarLocal', idSite=idSite)}}" role="button"><i class="fa-solid fa-plus"></i> Novo</a>
          <a class="btn btn-warning ml-3" href=" " role="button"><i class="fa-regular fa-file-pdf"></i> PDF</a>
        </div>
      </div>
    </form>
  </header>
  <main>
    <table class="table table-hover text-center">
      <thead>
        <tr class="table-secondary">
          <th scope="col"><a href="#">Id</a></th>
          <th scope="col"><a href="#">Local</a></th>
          <th scope="col"><a href="#">Site</a></th>
          <th scope="col">Ação</th>
        </tr>
      </thead>
      <tbody>
        {% for local in locais%}
          <tr>
            <th scope="row">{{local.id}}</th>
            <td>{{local.descricao}}</td>
            <td>{{local.nome}}</td>
            <td>
              <a class="btn btn-info" href="{{url_for('main.updateLocal', id_local=local.id)}}" role="button"><i class="fa-solid fa-pen-to-square"></i> Editar</a>
              <a href="#" onclick="excluirLocal('{{local.id}}')" role="button" class="btn btn-danger ml-3" data-toggle="modal" data-target="#deleteModalCenter"><i class="fa-solid fa-trash-can"></i> Excluir</a>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </main>
  <!-- Modal -->
  <div class="modal fade" id="deleteModalCenter" tabindex="-1" role="dialog" aria-labelledby="deleteModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLongTitle">Excluir Local?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <span class="font-weight-bold">Se esse é o seu desejo então confirme selecionando Excluir, teste</span>
          <!-- <span id="teste_id"></span> -->          
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
          <form action="" method="POST">
            <input type="hidden" name="id_local" id="id_local">
            <input type="submit" class="btn btn-danger" value="Excluir">
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

app/templates/main/site.html
{% extends 'layout2.html' %}
{% block content %}
  <header>
    <div class="jumbotron jumbotron-fluid mt-4">
      <div class="container">
        <h1 class="display-4"><i class="fa-solid fa-building-columns"></i> Site cadastrados no sistema</h1>
        <p class="lead">Relação de todos os site cadastrado no sistema.</p>
      </div>
    </div>
    <form action="{{url_for('main.consultaSite')}}" method="POST" class="ml-3 mb-4">
      {{form.hidden_tag()}}
      <div class="form-group">
        <div class="row">
          {{form.consulta(class="form-control col-md-5", placeholder="Digita aqui a consulta...")}}
          {{form.selection(class='form-control col-md-2 ml-3')}}
          <button type="submit" class="btn btn-success ml-4"><i class="fa-solid fa-magnifying-glass"></i> Consultar</button>
          <a class="btn btn-primary ml-3" href="{{url_for('main.registrar_site')}}" role="button"><i class="fa-solid fa-plus"></i> Novo</a>
        </div>
      </div>
    </form>
  </header>
  <main>
    <table class="table table-hover text-center">
      <thead>
        <tr class="table-secondary">
          <th scope="col"><a href="#">Id</a></th>
          <th scope="col"><a href="#">Site</a></th>
          <th scope="col"><a href="#">Cidade</a></th>
          <th scope="col"><a href="#">CEP</a></th>
          <th scope="col">Ação</th>
        </tr>
      </thead>
      <tbody>
        {% for site in sites%}
          <tr>
            <th scope="row">{{site.id}}</th>
            <td>{{site.nome}}</td>
            <td>{{site.cidade}}</td>
            <td>{{site.cep}}</td>
            <td>
              <a class="btn btn-info" href="{{url_for('main.update_site', id_site=site.id)}}" role="button"><i class="fa-solid fa-pen-to-square"></i> Editar</a>
              <a href="#" onclick="excluirSite('{{site.id}}')" role="button" class="btn btn-danger ml-3" data-toggle="modal" data-target="#deleteModalCenter"><i class="fa-solid fa-trash-can"></i> Excluir</a>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </main>
  <!-- Modal -->
  <div class="modal fade" id="deleteModalCenter" tabindex="-1" role="dialog" aria-labelledby="deleteModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLongTitle">Excluir Site?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <span class="font-weight-bold">Se esse é o seu desejo então confirme selecionando Excluir</span>
          <!-- <span id="teste_id"></span> -->          
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
          <form action="{{url_for('main.delete_site')}}" method="POST">
            <input type="hidden" name="id_site" id="id_site">
            <input type="submit" class="btn btn-danger" value="Excluir">
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}