app/controllers/main/routes.py
from flask import render_template, flash, redirect, url_for, Blueprint, request, abort
from app.controllers.main.form import (
    SiteForm, LocalAtendimento, SiteUpdateForm, UpdateLocal, AreaForm, localViewForm, AreaViewForm, ConsultaSiteForm)
from flask_login import current_user, login_required
from app.models.bdMonitora import Enderecos, Sites, PontoAtendimentos, Areas
from app import db
from sqlalchemy import exc, and_
from app.controllers.equipamento.monitora import Monitora
from datetime import date, datetime


main = Blueprint('main', __name__)


@main.route('/')
@main.route('/home')
@main.route('/monitora')
def home():
    # print(current_user.id)
    monitora = Monitora()
    return render_template('main/home.html', title='Home', local='São Carlos', computador=monitora.computadoresView())


@main.route('/site')
@login_required
def site():
    # print(current_user.permissoes)
    form = ConsultaSiteForm()
    if (current_user.permissoes[0].leitura or current_user.permissoes[0].escrita) and (current_user.permissoes[0].leitura or current_user.permissoes[0].escrita) and current_user.ativo:
        sites = db.session.query(Sites.id, Sites.nome, Enderecos.rua, Enderecos.cep, Enderecos.cidade).join(
            Sites, Enderecos.id == Sites.id).all()
        return render_template('main/site.html', title='Site', sites=sites, form=form)
    else:
        abort(403)

@main.route('/consultaSite', methods=['POST'])
@login_required
def consultaSite():
    if (current_user.permissoes[0].leitura or current_user.permissoes[0].escrita) and current_user.ativo:
        form = ConsultaSiteForm()
        if form.validate_on_submit():
            consulta = '%'+form.consulta.data+'%'
            selection = form.selection.data
            if selection == 'Site':
                sites = db.session.query(Sites.id, Sites.nome, Enderecos.rua, Enderecos.cep, Enderecos.cidade).join(Sites, Enderecos.id == Sites.id).filter(Sites.nome.like(consulta)).all()
            elif selection == 'Cidade':
                sites = db.session.query(Sites.id, Sites.nome, Enderecos.rua, Enderecos.cep, Enderecos.cidade).join(Sites, Enderecos.id == Sites.id).filter(Enderecos.cidade.like(consulta)).all()
            elif selection == 'Cep':
                 sites = db.session.query(Sites.id, Sites.nome, Enderecos.rua, Enderecos.cep, Enderecos.cidade).join(Sites, Enderecos.id == Sites.id).filter(Enderecos.cep.like(consulta)).all()
            else:
                sites = db.session.query(Sites.id, Sites.nome, Enderecos.rua, Enderecos.cep, Enderecos.cidade).join(Sites, Enderecos.id == Sites.id).all()
            return render_template('main/site.html', title='Site', sites=sites, form=form)
        else:
            flash('Erro, verificar dados informados ', 'danger')
            sites = db.session.query(Sites.id, Sites.nome, Enderecos.rua, Enderecos.cep, Enderecos.cidade).join(Sites, Enderecos.id == Sites.id).all()
            return render_template('main/site.html', title='Site', sites=sites, form=form)
    else:
        abort(403)

@main.route('/site/new', methods=['GET', 'POST'])
@login_required
def registrar_site():
    if (current_user.permissoes[0].leitura or current_user.permissoes[0].escrita) and current_user.ativo:
        form = SiteForm()
        if form.validate_on_submit():
            endereco = Enderecos(cidade=form.cidade.data.title(), rua=form.rua.data.title(), cep=form.cep.data)
            db.session.add(endereco)
            db.session.commit()
            site = Sites(nome=form.nome.data.title(), idEndereco=endereco.id)
            db.session.add(site)
            db.session.commit()
            areas = ['Estoque', 'Inventario', 'Descarte']
            for area in areas:
                a = Areas(nome=area, site=[site])
                db.session.add(a)
                db.session.commit()

            flash('Site Cadastrado com sucesso!', 'success')
            return redirect(url_for('main.site'))
        return render_template('main/registrar_site.html', title='Registrar Site', form=form)
    else:
        abort(403)


@main.route('/site/<int:id_site>/update', methods=['GET', 'POST'])
@login_required
def update_site(id_site):
    if (current_user.permissoes[0].leitura or current_user.permissoes[0].escrita) and current_user.ativo:
        try:
            endereco = Enderecos.query.get_or_404(id_site)
            site = Sites.query.filter_by(idEndereco=endereco.id).first_or_404()
        except Exception as e:
            print(f'Erro ao consultar: {e}')
        form = SiteUpdateForm()
        if form.validate_on_submit():
            endereco.rua = form.rua.data.title()
            endereco.cep = form.cep.data
            endereco.cidade = form.cidade.data.title()
            site.nome = form.nome.data.title()
            db.session.commit()
            flash('Dados atualizados com sucesso', 'success')
            return redirect(url_for('main.site'))
        elif request.method == 'GET':
            form.rua.data = endereco.rua
            form.cep.data = endereco.cep
            form.cidade.data = endereco.cidade
            form.nome.data = site.nome
        return render_template('main/update_site.html', title='Update Site', legenda='Editar Site', id_site=id_site, form=form)
    else:
        abort(403)


@main.route('/site/delete', methods=['POST'])
@login_required
def delete_site():
    if (current_user.permissoes[0].leitura or current_user.permissoes[0].escrita) and current_user.ativo:
        id_site = request.form.get('id_site')
        endereco = Enderecos.query.get_or_404(id_site)
        site = Sites.query.filter_by(idEndereco=endereco.id).first_or_404()
        if site.id != 1:
            db.session.delete(endereco)
            db.session.delete(site)
            db.session.commit()
            flash('Site removido conforme solicitado', 'success')
        else:
            flash('Restrição de segurança - Site não pode ser removido', 'danger')
        return redirect(url_for('main.site'))
    else:
        abort(403)


@main.route('/local/<int:idSite>/consulta', methods=['GET', 'POST'])
@login_required
def localizarPA(idSite):
    if (current_user.permissoes[0].leitura or current_user.permissoes[0].escrita) and current_user.ativo:
        print(f'Site ID: {idSite}')
        locais = db.session.query(PontoAtendimentos.id, PontoAtendimentos.descricao, Sites.nome).join(
            PontoAtendimentos, Sites.id == PontoAtendimentos.idSite).filter(Sites.id == idSite).all()
        if locais:
            return render_template('main/local.html', title='Ponto Atendimento', locais=locais, idSite=idSite, legenda='Pontos de  Atendimentos', descricao=f'Relação de todos as P.A.s cadastradas no Site: {locais[0].nome}')
        else:
            return render_template('main/local.html', title='Ponto Atendimento', locais=locais, idSite=idSite, legenda='Pontos de  Atendimentos', descricao='Não existe Ponto atendimento para Local selecionado.')
    else:
        abort(403)


@main.route('/local/view')
@login_required
def localView():
    if (current_user.permissoes[0].leitura or current_user.permissoes[0].escrita) and current_user.ativo:
        form = localViewForm()
        try:
            sites = db.session.query(Sites).all()
        except Exception as e:
            print(f'Error: {e}')
        return render_template('main/local_view.html', title='Ponto Atendimento', legenda='Pontos de Atendimentos', descricao='Seleciono o Site que deseja acessar', sites=sites, form=form)
    else:
        abort(403)


# @main.route('/local/registrarLocal', methods=['GET', 'POST'])
@main.route('/local/<int:idSite>/novo', methods=['GET', 'POST'])
@login_required
def registrarLocal(idSite):
    if (current_user.permissoes[0].leitura or current_user.permissoes[0].escrita) and current_user.ativo:
        form = LocalAtendimento()
        if form.validate_on_submit():
            site = Sites.query.filter_by(nome=form.localSelect.data).first()
            if site:
                local = PontoAtendimentos(descricao=form.localPa.data.upper(), idSite=site.id)
                db.session.add(local)
                db.session.commit()
                flash('Ponto de atendimento cadastrado com sucesso', 'success')
                return redirect(url_for('main.localizarPA', idSite=idSite))
            else:
                flash('Ponto de atendimento cadastrado com sucesso', 'danger')
                return redirect(url_for('main.registrarPa'))
        elif request.method == 'GET':
            try:
                site = Sites.query.get(idSite)
            except Exception as e:
                print(f'Error: {e}')
            form.localSelect.choices = [site.nome]
            return render_template('main/create_ponto_atendimento.html', title='Novo Ponto Atendimento', legenda='Ponto Atendento (P.A)', descricao=f'Preencha a descrição da P.A para realizar o cadastro no site: {site.nome}', form=form, idSite=idSite)

    else:
        abort(403)


@main.route('/local/<int:id_local>/update', methods=['GET', 'POST'])
@login_required
def updateLocal(id_local):
    if (current_user.permissoes[0].leitura or current_user.permissoes[0].escrita) and current_user.ativo:
        form = UpdateLocal()
        try:
            localForm = db.session.query(PontoAtendimentos.descricao, PontoAtendimentos.idSite, PontoAtendimentos.id, Sites.nome).join(
                Sites, Sites.id == PontoAtendimentos.idSite).filter(PontoAtendimentos.id == id_local).first_or_404()
            # print(local)
            # precisa verificar a consulta para atualizar local e o site
        except Exception as e:
            print(f'Erro ao realizar consulta{e}')
            abort(404)
        if form.validate_on_submit():
            try:
                local = PontoAtendimentos.query.get_or_404(id_local)
                site = Sites.query.filter(
                    Sites.nome == form.localSelect.data).first_or_404()
            except Exception as e:

app/templates/layout.html
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="{{url_for('static', filename='img/favicon.ico')}}" type="image/x-icon">
    <link rel="stylesheet" href="{{url_for('static', filename='css/main.css')}}">
    <link rel="stylesheet" href="{{url_for('static', filename='css/bootstrap.min.css')}}">
    <link rel="stylesheet" href="{{url_for('static', filename='css/fontawesome-free/css/fontawesome.css')}}">
    <link rel="stylesheet" href="{{url_for('static', filename='css/fontawesome-free/css/solid.css')}}">
    <link rel="stylesheet" href="{{url_for('static', filename='css/fontawesome-free/css/regular.css')}}">
    <link rel="stylesheet" href="{{url_for('static', filename='css/home.css')}}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Courgette&display=swap" rel="stylesheet">
    {% if title %}
    <title>Monitora - {{title}}</title>
    {% else %}
    <table>Monitora</table>
    {% endif %}
</head>

<body>
    <header>
        <div class="collapse bg-dark" id="navbarHeader">
            <div class="container">
                <div class="row">
                    <div class="col-sm-8 col-md-7 py-4">
                        <h4 class="text-white">Sobre</h4>
                        <p class="text-muted">
                            Monitora foi desenvolvida por: José Edmar de Siqueira, Analista do Sim 24 Horas para monitorar os equipamentos conectado a rede MAPFRE, 
                            esse monitoramento pode ser realizado em qual quer local desde que seja cadastrado no sistema.
                            Monitora também é um sistema de controle de estoque, para melhor integração e controle dos dispositivos que estão inloco ou no  inventário.
                        </p>
                    </div>
                    <div class="col-sm-4 offset-md-1 py-4">
                        <h4 class="text-white">Opções</h4>
                        <ul class="list-unstyled">
                            {% if current_user.is_authenticated %}
                                <li><a href="{{url_for('user.logout')}}" class="text-white"> <i class="fa-solid fa-right-from-bracket"></i> Sair</a></li>
                                {% if (current_user.permissoes[0].leitura or current_user.permissoes[0].escrita) and current_user.ativo%}
                                    <li><a href="{{url_for('equipamento.inventarioView')}}" class="text-white"><i class="fa-solid fa-gears"></i> Tela Administrativa</a></li>
                                {% endif %}
                            {% else %}
                                <li><a href="{{url_for('user.login')}}" class="text-white"><i class="fa-solid fa-right-from-bracket"></i> Logar</a></li>
                            {% endif %}
                            <li><a href="#" class="text-white"><i class="fa-regular fa-envelope"></i> Contactar Suporte</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="navbar navbar-dark bg-dark shadow-sm">
            <div class="container d-flex justify-content-between">
                <a href="{{url_for('main.home')}}" class="navbar-brand d-flex align-items-center">
                    <strong class="logo">MAPFRE</strong>
                </a>
                <a href="{{url_for('main.home')}}" class="navbar-brand d-flex align-items-center">
                    <strong>Site - {{local}}</strong>
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader"
                    aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </div>

    </header>
    
    {% block content %}  {% endblock %}
    <footer>
        <hr>
        <p>&copy; Desenvolvido em 2022-2022</p>
    </footer>

    <script src="{{url_for('static', filename='js/jquery.min.js')}}"></script>
    <script src="{{url_for('static', filename='js/popper.min.js')}}"></script>
    <script src="{{url_for('static', filename='js/bootstrap.min.js')}}"></script>
    <script src="{{url_for('static', filename='js/holder.min.js')}}"></script>
</body>

</html>

app/templates/layout2.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="{{url_for('static', filename='img/favicon.ico')}}" type="image/x-icon">
    <link rel="stylesheet" href="{{url_for('static', filename='css/main.css')}}">
    <link rel="stylesheet" href="{{url_for('static', filename='css/bootstrap.min.css')}}">
    <link rel="stylesheet" href="{{url_for('static', filename='css/home.css')}}">
    <link rel="stylesheet" href="{{url_for('static', filename='css/admin.css')}}">
    <link rel="stylesheet" href="{{url_for('static', filename='css/listagem.css')}}">
    <link rel="stylesheet" href="{{url_for('static', filename='css/estoqueMudarLocal.css')}}">
    <link rel="stylesheet" href="{{url_for('static', filename='css/fontawesome-free/css/fontawesome.css')}}">
    <link rel="stylesheet" href="{{url_for('static', filename='css/fontawesome-free/css/solid.css')}}">
    <link rel="stylesheet" href="{{url_for('static', filename='css/fontawesome-free/css/regular.css')}}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Courgette&display=swap" rel="stylesheet">

    {% if title %}
    <title>Monitora - {{title}}</title>
    {% else %}
    <table>Monitora</table>
    {% endif %}

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <a class="navbar-brand" href="{{url_for('main.home')}}"><i class="fa-solid fa-house"></i> Monitora</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbars" aria-controls="navbars" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbars">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item px-3 active">
              <a class="nav-link" href="{{url_for('equipamento.inventarioView')}}"><i class="fa-solid fa-clipboard-list"></i> Inventários<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item px-3 dropdown">
              <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" aria-expanded="false"><i class="fa fa-sliders"></i> Controles</a>
              <div class="dropdown-menu">
                <a class="dropdown-item" href="{{url_for('est.estoqueView')}}"><i class="fa-solid fa-table"></i> Estoque</a>
                <a class="dropdown-item" href="#"><i class="fa-solid fa-laptop-code"></i> Notebook</a>
                <a class="dropdown-item" href="#"><i class="fa-solid fa-left-right"></i> Emprestimos</a>
                <a class="dropdown-item" href="#"><i class="fa fa-trash"></i> Descarte</a>
                <!-- <a class="dropdown-item" href="{{url_for('main.localView')}}"><i class="fa-solid fa-magnifying-glass-location"></i> Local-Atendimento</a>
                <a class="dropdown-item" href="{{url_for('main.areaView')}}"><i class="fa-solid fa-warehouse"></i> Área</a> -->
              </div>
            </li>=
            <li class="nav-item px-3 dropdown">
              <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" aria-expanded="false"><i class="fa-solid fa-gears"></i> Adm-site</a>
              <div class="dropdown-menu">
                <a class="dropdown-item" href="{{url_for('main.site')}}"><i class="fa-solid fa-map-location"></i> Site</a>
                <a class="dropdown-item" href="{{url_for('main.localView')}}"><i class="fa-solid fa-magnifying-glass-location"></i> Local-Atendimento</a>
                <a class="dropdown-item" href="{{url_for('equipamento.equipamentoView')}}"><i class="fa-solid fa-laptop-code"></i> Equipamento</a>
                <a class="dropdown-item" href="{{url_for('main.areaView')}}"><i class="fa-solid fa-warehouse"></i> Área</a>
              </div>
            </li>
            {% if current_user.permissoes[0].adminUser %}
              <li class="nav-item px-3 dropdown">
                <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" aria-expanded="false"><i class="fa-solid fa-users-gear"></i> Usuários</a>
                <div class="dropdown-menu">
                  <a class="dropdown-item" href="{{url_for('user.usuarioSite')}}"><i class="fa-solid fa-list-ol"></i> Listar usuário</a>
                </div>
              </li>
            {% endif %}
          </ul>
          <ul class="navbar-nav flex-row ml-md-auto d-none d-md-flex">
            <li class="nav-item">
              <span class="text-light"><i class="fa-solid fa-user-check text-success"></i> {{current_user.login}}</span>
            </li>
          </ul>
          <ul class="navbar-nav flex-row ml-md-auto d-none d-md-flex">
            <li class="nav-item">
              <a class="nav-link" href="{{url_for('user.logout')}}"><i class="fa-solid fa-right-from-bracket"></i> Sair</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container mt-4">
      
      {% with messages = get_flashed_messages(with_categories=true)%}
          {% if messages %}
              {% for category, message in messages %}
                  <div class="alert alert-{{category}}">
                      {{message}}
                  </div>
              {% endfor %}
          {%endif%}
      {%endwith%}

      {% block content %}  {% endblock %}

    </div>

    <footer>
      <hr>
      <p>&copy; Desenvolvido em 2022-2022</p>
    </footer>
    <script src="{{url_for('static', filename='js/jquery.min.js')}}"></script>
    <script src="{{url_for('static', filename='js/popper.min.js')}}"></script>
    <script src="{{url_for('static', filename='js/bootstrap.min.js')}}"></script>
    <script src="{{url_for('static', filename='js/holder.min.js')}}"></script>
    <script src="{{url_for('static', filename='js/scriptModal.js')}}"></script>
    <script src="{{url_for('static', filename='js/mudarEstoque.js')}}"></script>
    <script>
      $(function () {
        $('[data-toggle="popover"]').popover()
      })
    </script>
  </body>
</html>

app/templates/local.html
{% extends 'layout2.html' %}
{% block content %}
  <header>
    <div class="jumbotron jumbotron-fluid mt-4">
      <div class="container">
        <h1 class="display-4">Local Disposito on Site</h1>
        <p class="lead">
          Relação de todos os Locais onde é possível equipamento ficar.
        </p>
      </div>
    </div>
    <form action="#" class="ml-3 mb-4">
      <div class="form-group">
        <div class="row">
          <input type="text" class="form-control col-md-5" name="consulta" placeholder="Digita aqui a consulta"/>
          <select class="form-control col-md-2 ml-3" name="campo" id="">
            <option value="pa">Local</option>
            <option value="site">Site</option>
          </select>
          <button type="submit" class="btn btn-success ml-4"><i class="fa-solid fa-magnifying-glass"></i> Consultar</button>
          <a class="btn btn-primary ml-3" href="{{url_for('main.registrarLocal')}}" role="button"><i class="fa-solid fa-plus"></i> Novo</a>
        </div>
      </div>
    </form>
  </header>
  <main>
    <table class="table table-hover text-center">
      <thead>
        <tr class="table-secondary">
          <th scope="col"><a href="#">Id</a></th>
          <th scope="col"><a href="#">Local</a></th>
          <th scope="col"><a href="#">Site</a></th>
          <th scope="col">Ação</th>
        </tr>
      </thead>
      <tbody>
        {% for local in locais%}
          <tr>
            <th scope="row">{{local.id}}</th>
            <td>{{local.localizadoEm}}</td>
            <td>{{local.siteNome}}</td>
            <td><a class="btn btn-info" href="#" role="button"><i class="fa-solid fa-pen-to-square"></i> Editar</a></td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </main>
{% endblock content %}

app/templates/localizacaoPa.html
{% extends 'layout2.html' %}
{% block content %}
  <header>
    <div class="jumbotron jumbotron-fluid mt-4">
      <div class="container">
        <h1 class="display-4">Pontos de Atendimentos</h1>
        <p class="lead">
          Relação de todos os pontos de atendimentos cadastrado no sistema.
        </p>
      </div>
    </div>
    <form action="#" class="ml-3 mb-4">
      <div class="form-group">
        <div class="row">
          <input type="text" class="form-control col-md-5" name="consulta" placeholder="Digita aqui a consulta"/>
          <select class="form-control col-md-2 ml-3" name="campo" id="">
            <option value="serial">Nome</option>
            <option value="patrimonio">Cidade</option>
            <option value="local">CEP</option>
          </select>
          <button type="submit" class="btn btn-success ml-4"><i class="fa-solid fa-magnifying-glass"></i> Consultar</button>
          <a class="btn btn-primary ml-3" href="{{url_for('main.registrar_site')}}" role="button"><i class="fa-solid fa-plus"></i> Novo</a>
        </div>
      </div>
    </form>
  </header>
  <main>
    <table class="table table-hover text-center">
      <thead>
        <tr class="table-secondary">
          <th scope="col"><a href="#">Id</a></th>
          <th scope="col"><a href="#">Site</a></th>
          <th scope="col"><a href="#">Cidade</a></th>
          <th scope="col"><a href="#">CEP</a></th>
          <th scope="col">Ação</th>
        </tr>
      </thead>
      <tbody>
        {% for site in sites%}
          <tr>
            <th scope="row">{{site.id}}</th>
            <td>{{site.siteNome}}</td>
            <td>{{site.cidade}}</td>
            <td>{{site.cep}}</td>
            <td><a class="btn btn-info" href="#" role="button"><i class="fa-solid fa-pen-to-square"></i> Editar</a></td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </main>
{% endblock content %}

app/templates/usuario.html
{% extends 'layout2.html' %}
{% block content %}
  <header>
    <div class="jumbotron jumbotron-fluid mt-4">
      <div class="container">
        <h1 class="display-4">Usuários cadastrados no sistema</h1>
        <p class="lead">
          Relação de todos os usuários cadastrado no sistema.
        </p>
      </div>
    </div>
    <form action="#" class="ml-3 mb-4">
      <div class="form-group">
        <div class="row">
          <input type="text" class="form-control col-md-5" name="consulta" placeholder="Digita aqui a consulta"/>
          <select class="form-control col-md-2 ml-3" name="campo" id="">
            <option value="serial">Nome</option>
            <option value="patrimonio">Login</option>
            <option value="local">E-mail</option>
          </select>
          <button type="submit" class="btn btn-success ml-4"><i class="fa-solid fa-magnifying-glass"></i> Consultar</button>
          <a class="btn btn-primary ml-3" href="{{url_for('user.novo_usuario')}}" role="button"><i class="fa-solid fa-user-plus"></i> Novo</a>
        </div>
      </div>
    </form>
  </header>
  <main>
    <table class="table table-hover text-center">
      <thead>
        <tr class="table-secondary">
          <th scope="col"><a href="#">Id</a></th>
          <th scope="col"><a href="#">Nome</a></th>
          <th scope="col"><a href="#">Login</a></th>
          <th scope="col"><a href="#">Email</a></th>
          <th scope="col"><a href="#">Site</a></th>
          <th scope="col">Ação</th>
        </tr>
      </thead>
      <tbody>
        {% for user in usuarios%}
          {% if user.login == 'Admin'%}
          {% else %}
            <tr>
              <th scope="row">{{user.id}}</th>
              <td>{{user.userNome}}</td>
              <td>{{user.login}}</td>
              <td>{{user.email}}</td>
              <td>{{user.siteNome}}</td>
              <td><a class="btn btn-info" href="#" role="button"><i class="fa-solid fa-pen-to-square"></i> Editar</a></td>
            </tr>
          {% endif %}
        {% endfor %}
      </tbody>
    </table>
  </main>
{% endblock content %}